- central-query/pom.xml
- pom.xml
For version change and source-code reorg
> Correct redundant artifact versioning

- central-query/src/main/etc/central-query_supervisor.conf
- central-query/src/main/etc/configuration.yaml
http://dropwizard.github.io/dropwizard/0.6.2/manual/core.html#configuration-defaults details requestLog config file syntax.
> Fixes ZEN-18412, ZEN-18418

- central-query/src/main/java/org/zenoss/app/metricservice/api/impl/IHasShortcut.java
- central-query/src/main/java/org/zenoss/app/metricservice/buckets/Buckets.java
- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
> Revert "Feature/zen 18491" didn't want to check in valuesById

- central-query/src/main/resources/api/nv.d3.min.js
This change simply copies over the patched nvd3 library from this PR https://github.com/zenoss/nvd3/pull/1
> add valueFormatter to area chart

- central-query/src/main/java/org/zenoss/app/metricservice/api/impl/OpenTSDBClient.java
cherry-pick pull-request #203
(committed by "zendev port cherry-pick")
> Fixes ZEN-20528

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
For [ZEN-20313](https://jira.zenoss.com/browse/ZEN-20313)
> Add capacity footer to query service

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
This reverts commit 3a16f1bd4ef6289e206d7a2703517cd2798f8c1f.
Pulling this out until the capacity feature for ucspm reports is totally
ready.
> Revert "Add capacity footer to query service"

- central-query/src/main/java/org/zenoss/app/metricservice/health/OpenTsdbHealthCheck.java
> Revert "Close InputStream and HttpURLConnection when we make a healthcheck ag…"

- central-query/src/main/etc/configuration.yaml
- central-query/src/main/js/visualization/src/polyfills.js
- central-query/src/main/resources/api/visualization.js
This pulls a couple of forgotten fixes into support/5.1.x that should be there, I'm fairly sure:
https://github.com/zenoss/query/pull/208 for https://jira.zenoss.com/browse/ZEN-20495
and
https://github.com/zenoss/query/pull/220 for https://jira.zenoss.com/browse/ZEN-18713
> port a couple of forgotten fixes

- central-query/src/main/js/visualization/src/charts/area.js
- central-query/src/main/js/visualization/src/charts/line.js
- central-query/src/main/resources/api/charts/area.js
- central-query/src/main/resources/api/charts/line.js
Fixing https://jira.zenoss.com/browse/CC-1891
> ensure legendState is present before iterating it

- central-query/src/main/java/org/zenoss/app/metricservice/api/metric/impl/MetricService.java
depends on https://github.com/zenoss/zenoss-prodbin/pull/1589
> if rpn expression is sent then result needs to be calculated value

- central-query/src/main/java/org/zenoss/app/metricservice/api/configs/MetricServiceConfig.java
- central-query/src/main/java/org/zenoss/app/metricservice/api/impl/OpenTSDBMetricStorage.java
cherry-pick pull-request #241
(committed by "zendev port cherry-pick")
> Fixes ZEN-23199

- central-query/pom.xml
- central-query/src/main/java/org/zenoss/app/metricservice/api/impl/OpenTSDBQueryReturn.java
- central-query/src/test/java/org/zenoss/app/metricservice/api/metric/remote/MetricResourcesTest.java
- central-query/src/test/java/org/zenoss/app/metricservice/v2/remote/ResourcesTest.java
Cherry-picked pull/245
Pull request created by zendev port
> Please review branch feature/ZEN-23807

- central-query/src/main/java/org/zenoss/app/metricservice/api/metric/remote/StatusResource.java
Cherry-picked pull/235
Pull request created by zendev port
> Please review branch feature/ZEN-23867

- central-query/src/main/bin/central-query.sh
Add new option which will kill Central Query instance when it will
get OOM
> ZEN-23521: Add new option to process once it OOM

- central-query/src/main/bin/central-query.sh
This is cherry-pick from https://github.com/zenoss/query/pull/249
> ZEN-24074: Add new option to process once it OOM

- central-query/src/main/java/org/zenoss/app/metricservice/api/metric/remote/StatusResource.java
This is port from : https://github.com/zenoss/query/pull/235
> ZEN-23867: add new healthchecks

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
[Jira](https://jira.zenoss.com/browse/ZEN-25826)
Here I make use of newly introduced settings from zenoss/zenoss-prodbin#1999
> ZEN-25826 Use user defined date format

- README.md
- central-query-lib/pom.xml
- central-query/pom.xml
- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
- pom.xml
Fix change aggregator function for downsampling to avoid losing precision on representing min/max values.
[Jira](https://jira.zenoss.com/browse/ZEN-25462)
> ZEN-25462 Graphs not displaying the actual max value correctly

- README.md
- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
> Revert "ZEN-25462 Graphs not displaying the actual max value correctly"

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
Fix added 2 additional queries for representing min/max values in the legend field.
[Jira](https://jira.zenoss.com/browse/ZEN-25462)
> ZEN-25462 add query for max values

- central-query/src/main/js/visualization/src/charts/area.js
- central-query/src/main/js/visualization/src/charts/line.js
- central-query/src/main/resources/api/charts/area.js
- central-query/src/main/resources/api/charts/line.js
[Jira](https://jira.zenoss.com/browse/ZEN-26778)
> ZEN-26778 Graphs - Pop up windows can be hidden

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/js/visualization/src/visualization.js
- central-query/src/main/resources/api/visualization.js
> Revert "Feature/zen 26864 cdk improvements"

- README.md
- central-query-lib/src/main/java/org/zenoss/app/metricservice/api/model/Aggregator.java
https://jira.zenoss.com/browse/CC-3285
For CC-3285, we need to have access to other aggregators.
> Add other OpenTSDB aggregators

- central-query-lib/pom.xml
- central-query/pom.xml
- pom.xml
Just bumping develop, following 0.1.17 release.
> Bump version to 0.1.18-SNAPSHOT

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
https://jira.zenoss.com/browse/CC-3327
We might not have the Zenoss object, like when we're in CC.
> CC-3327: Check that Zenoss isn't undefined before trying to use USER_DATE_FORMAT

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
Re-adding this to develop as it was previously removed pending the 5.2.2 release
> ZEN-26883 graph refresh improvements

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
[Jira](https://jira.zenoss.com/browse/ZEN-25462)
Those changes were originally introduced in #268 but then reverted in #272 but now need to be merged again (see comments on Jira) 🙂
> ZEN-25462: Graphs not displaying the actual max value correctly

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
[Jira](https://jira.zenoss.com/browse/ZEN-27167)
> ZEN-27167 Using 'zoom in' on a graph of 'expand graph' option

- central-query/src/main/resources/api/visualization.js
> ZEN-26925 Chart Y axis values

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
[jira](https://jira.zenoss.com/browse/ZEN-27108)
Fixed `rowKey` for binding `Projected Values` with proper datapoint
> ZEN-27108 No Projected Values displayed

- central-query/src/main/resources/api/visualization.js
Add 3 lines that failed to be included into the ZEN-27340 check-ins.
> ZEN-27581 legend scrollbars

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
https://jira.zenoss.com/browse/ZEN-27561
This adds projections to the lower legend, which were only previously in the upper legend (now hidden).
> Feature/zen 27561.2

- central-query-lib/pom.xml
- central-query/pom.xml
- pom.xml
After releasing Query, bump to 0.1.25-SNAPSHOT
> Feature/bump version0.1.25 snapshot

- central-query/src/main/js/visualization/src/charts/line.js
Fixed clipping issue on line charts extending into header/footer area of chart.
> ZEN-28780 Line charts draw outside the chart area

- central-query/src/main/js/visualization/package.json
- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
[Jira](https://jira.zenoss.com/browse/ZEN-29274)
> change avg calculation for graphs footer

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/js/visualization/src/charts/line.js
- central-query/src/main/resources/api/charts/line.js
- central-query/src/main/resources/api/visualization.js
Ensure charts can be read even for narrow browsers
> ZEN-29235 Narrow browser graph improvements

- central-query/src/main/js/visualization/src/Chart.js
- central-query/src/main/resources/api/visualization.js
[Jira&DEMO](https://jira.zenoss.com/browse/ZEN-29234)
> add percent sign to multigraph summary legend numbers

- central-query-lib/pom.xml
- central-query/pom.xml
- pom.xml
https://jira.zenoss.com/browse/ZING-1443
Bump dev version after releasing version 0.1.32
> Feature/bump version0.1.33dev

- central-query-lib/pom.xml
- central-query/pom.xml
- pom.xml
> Bump version

- central-query-lib/pom.xml
- central-query/pom.xml
- pom.xml
> Bump develop to 0.1.39
